# Generated by Django 2.0.5 on 2018-05-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=254)),
                ('suburb', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('postcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], max_length=2)),
                ('dob', models.DateField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], max_length=2)),
                ('dob', models.DateField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('other_phone', models.CharField(max_length=10, null=True)),
                ('facebook', models.CharField(max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], max_length=2)),
                ('dob', models.DateField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profile.Student')),
                ('gender_pref', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], max_length=2, null=True)),
                ('language_pref', models.CharField(choices=[('EN', 'English'), ('MA', 'Mandarin'), ('JA', 'Japanese'), ('GE', 'German'), ('FR', 'French'), ('SP', 'Spanish')], max_length=2, null=True)),
                ('classtime_pref', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profile.Teacher')),
                ('english', models.BooleanField()),
                ('mandarin', models.BooleanField()),
                ('japanese', models.BooleanField()),
                ('german', models.BooleanField()),
                ('french', models.BooleanField()),
                ('spanish', models.BooleanField()),
                ('piano', models.BooleanField()),
                ('guitar', models.BooleanField()),
                ('tuba', models.BooleanField()),
                ('harmonium', models.BooleanField()),
                ('trumpet', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.Address'),
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Student'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='teacher_pref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Teacher'),
        ),
    ]
