# Generated by Django 2.0.5 on 2018-05-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.AddField(
            model_name='parent',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='street_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='street_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='suburb',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='street_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='street_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='suburb',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='street_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='street_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='suburb',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='classtime_pref',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='gender_pref',
            field=models.CharField(blank=True, choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='language_pref',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('MA', 'Mandarin'), ('JA', 'Japanese'), ('GE', 'German'), ('FR', 'French'), ('SP', 'Spanish')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='teacher_pref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='facebook',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
