# Generated by Django 2.0.5 on 2018-05-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20180516_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.DateTimeField()),
                ('instrument', models.CharField(choices=[('PI', 'Piano'), ('GU', 'Guitar'), ('HA', 'Harmonium'), ('TU', 'Tuba'), ('TR', 'Trumpet')], max_length=2)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PI', 'Piano'), ('GU', 'Guitar'), ('HA', 'Harmonium'), ('TU', 'Tuba'), ('TR', 'Trumpet')], max_length=2)),
                ('cost', models.CharField(max_length=8)),
                ('condition', models.CharField(choices=[('DI', 'discard'), ('RE', 'repair'), ('GO', 'good'), ('EX', 'excellent'), ('NE', 'new')], max_length=2)),
                ('student', models.ManyToManyField(to='profile.Student')),
            ],
        ),
        migrations.AlterModelOptions(
            name='preferences',
            options={'verbose_name_plural': 'Preferences'},
        ),
        migrations.AlterModelOptions(
            name='qualifications',
            options={'verbose_name_plural': 'Qualifications'},
        ),
        migrations.AddField(
            model_name='preferences',
            name='instrument_pref',
            field=models.CharField(blank=True, choices=[('PI', 'Piano'), ('GU', 'Guitar'), ('HA', 'Harmonium'), ('TU', 'Tuba'), ('TR', 'Trumpet')], max_length=2, null=True),
        ),
    ]
