# Generated by Django 2.0.3 on 2018-05-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20180516_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.CharField(default='C32', max_length=3),
        ),
        migrations.AddField(
            model_name='parent',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='state',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='state',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Student'),
        ),
    ]
