# Generated by Django 2.0.3 on 2018-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20180519_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='room',
            field=models.CharField(max_length=3),
        ),
    ]
