# Generated by Django 2.0.3 on 2018-05-21 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20180521_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instrument', models.CharField(choices=[('PI', 'Piano'), ('GU', 'Guitar'), ('HA', 'Harmonium'), ('TU', 'Tuba'), ('TR', 'Trumpet')], max_length=2)),
                ('duration', models.CharField(choices=[('30', '30'), ('60', '60')], max_length=2)),
                ('cost', models.FloatField()),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Student')),
            ],
        ),
    ]
